version: '3.1'

services:

    wildfly:
      image: sulfur-backend
      build: .
      environment:
        TZ: America/Montevideo
        DB_HOST: db
        DB_NAME: sulfur
        DB_USER: sulfur_user
        DB_PASS: sulfur_pass
        LOGSTASH_HOST: logstash
      ports:
        - 8080:8080
        - 9990:9990
      links:
        - db
      volumes:
        - ./resources/deployments:/opt/jboss/wildfly/standalone/deployments

    db:
        image: postgres
        environment:
            POSTGRES_USER: sulfur_user
            POSTGRES_PASSWORD: sulfur_pass
            POSTGRES_DB: sulfur

    adminer:
        image: adminer
        links:
                - db
        ports:
            - 8081:8080