version: '3.1'

services:

    wildfly_REPLACE_PROJECT_NAME:
      image: REPLACE_IMAGE_NAME
      build: .
      environment:
        DB_HOST: ${DB_HOST}
        DB_NAME: REPLACE_PROJECT_NAME
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        LOGSTASH_HOST: ${LOGSTASH_HOST}
        VIRTUAL_HOST: REPLACE_URL_TEST
        LETSENCRYPT_HOST: REPLACE_URL_TEST
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        ZOHO_MAIL_FROM: ${ZOHO_MAIL_FROM}
        ZOHO_MAIL_PASS: ${ZOHO_MAIL_PASS}
        ROOT_PASSWORD: ${ROOT_PASSWORD}
      ports:
        - 8080


networks:
 default:
   external:
     name: nginx-proxy
